export const datalist = {
  totalPassengers: 93,
  totalPages: 10,
  data: [
    {
      _id: '63300ef9d333c8225b9a152b',
      name: 'SANCHOS',
      trips: 23,
      airline: [
        {
          id: 4,
          name: 'Emirates',
          country: 'Dubai',
          logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Emirates_logo.svg/150px-Emirates_logo.svg.png',
          slogan: 'From Dubai to destinations around the world.',
          head_quaters: 'Garhoud, Dubai, United Arab Emirates',
          website: 'www.emirates.com/',
          established: '1985',
        },
      ],
      __v: 0,
    },
    {
      _id: '63301161d333c8897f9a1561',
      name: 'New Passenger',
      trips: 3,
      airline: [
        {
          id: 2,
          name: 'Singapore Airlines',
          country: 'Singapore',
          logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/6/6b/Singapore_Airlines_Logo_2.svg/250px-Singapore_Airlines_Logo_2.svg.png',
          slogan: 'A Great Way to Fly',
          head_quaters: 'Airline House, 25 Airline Road, Singapore 819829',
          website: 'www.singaporeair.com',
          established: '1947',
        },
      ],
      __v: 0,
    },
    {
      _id: '63301f0dd333c8f4a89a15ab',
      name: 'ewqre',
      trips: 12,
      airline: [
        {
          _id: '5ef4a09eaab384a021750ce7',
          id: 12,
          name: 'Sri Lankan Airways',
          country: 'Sri Lanka',
          logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/9/9b/Qatar_Airways_Logo.svg/sri_lanka.png',
          slogan: 'From Sri Lanka',
          head_quaters: 'Katunayake, Sri Lanka',
          website: 'www.srilankaairways.com',
          established: '1990',
          __v: 0,
        },
      ],
      __v: 0,
    },
    {
      _id: '63302dfbd333c8577a9a1721',
      name: 'Mark 2',
      trips: 43,
      airline: [
        {
          id: 5,
          name: 'Eva Air',
          country: 'Taiwan',
          logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/ed/EVA_Air_logo.svg/250px-EVA_Air_logo.svg.png',
          slogan: 'Sharing the World, Flying Together',
          head_quaters:
            '376, Hsin-Nan Rd., Sec. 1, Luzhu, Taoyuan City, Taiwan',
          website: 'www.evaair.com',
          established: '1989',
        },
      ],
      __v: 0,
    },
    {
      _id: '63302e17d333c828879a1728',
      name: 'Lucy21',
      trips: 3,
      airline: [
        {
          id: 8,
          name: 'Thai Airways',
          country: 'Thailand',
          logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/5/58/Thai_Airways_Logo.svg/200px-Thai_Airways_Logo.svg.png',
          slogan: 'Smooth as Silk / I Fly THAI',
          head_quaters: 'Jom Phol Subdistrict, Chatuchak, Bangkok, Thailand',
          website: 'www.thaiairways.com',
          established: '1960',
        },
      ],
      __v: 0,
    },
    {
      _id: '633042abd333c894a19a1816',
      name: 'Stephan',
      trips: 6,
      airline: [
        {
          id: 6,
          name: 'Qantas',
          country: 'Austrailia',
          logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/0/02/Qantas_Airways_logo_2016.svg/300px-Qantas_Airways_logo_2016.svg.png',
          slogan: 'Spirit of Australia',
          head_quaters: 'Mascot, Sydney, Australia',
          website: 'qantas.com',
          established: '1920',
        },
      ],
      __v: 0,
    },
    {
      _id: '633046a4d333c8d5419a1861',
      name: 'John Doe',
      trips: 250,
      airline: [
        {
          id: 5,
          name: 'Eva Air',
          country: 'Taiwan',
          logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/ed/EVA_Air_logo.svg/250px-EVA_Air_logo.svg.png',
          slogan: 'Sharing the World, Flying Together',
          head_quaters:
            '376, Hsin-Nan Rd., Sec. 1, Luzhu, Taoyuan City, Taiwan',
          website: 'www.evaair.com',
          established: '1989',
        },
      ],
      __v: 0,
    },
    {
      _id: '633046d8d333c8f6119a1865',
      name: 'Darshan Mesta',
      trips: 250,
      airline: [
        {
          id: 6,
          name: 'Qantas',
          country: 'Austrailia',
          logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/0/02/Qantas_Airways_logo_2016.svg/300px-Qantas_Airways_logo_2016.svg.png',
          slogan: 'Spirit of Australia',
          head_quaters: 'Mascot, Sydney, Australia',
          website: 'qantas.com',
          established: '1920',
        },
      ],
      __v: 0,
    },
    {
      _id: '63304a4cd333c8d2629a18f2',
      name: 'Thillo Richter ',
      trips: 100,
      airline: [
        {
          id: 1,
          name: 'Quatar Airways',
          country: 'Quatar',
          logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/9/9b/Qatar_Airways_Logo.svg/300px-Qatar_Airways_Logo.svg.png',
          slogan: 'Going Places Together',
          head_quaters: 'Qatar Airways Towers, Doha, Qatar',
          website: 'www.qatarairways.com',
          established: '1994',
        },
      ],
      __v: 0,
    },
    {
      _id: '63304b83a0efd9227d4f8b7f',
      name: 'Thillo ',
      trips: 100,
      airline: [
        {
          id: 1,
          name: 'Quatar Airways',
          country: 'Quatar',
          logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/9/9b/Qatar_Airways_Logo.svg/300px-Qatar_Airways_Logo.svg.png',
          slogan: 'Going Places Together',
          head_quaters: 'Qatar Airways Towers, Doha, Qatar',
          website: 'www.qatarairways.com',
          established: '1994',
        },
      ],
      __v: 0,
    },
  ],
};
